id: I9F6BBA24
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:43:41+00:00'
last_modified: '2022-06-16T04:47:51.267617+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21782
  title: གཞོན་ནུ་དྲུག་གི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8348':
      image_group_id: I1KG23247
      title: Volume 1 of gzhon nu drug gi rtogs brjod/
      total_pages: 108
      order: 1
      base_file: 8348.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
